channels:
  - pyviz
  - conda-forge
  - defaults
dependencies:
  - geopandas
  - folium
  - altair
  - notebook
  - vega
  - nbserverproxy
  - param
  - pyviz_comms
  - datashader
  - holoviews
  - hvplot
  - bokeh
  - panel
  - tornado<6  
