dependencies:
  - nbserverproxy
  - pyviz:holoviews
  - pyviz::panel
  - pyviz::param
  - pyviz::hvplot
  - bokeh::bokeh
  - conda-forge::geopandas
  - conda-forge::folium
  - altair
  - notebook
  - vega
  - tornado<6
